
ifeq ($(CONFIG_SS_COREPRIMELITE),y)
obj-y += sensor_power_coreprimelite.o
else ifeq ($(CONFIG_SS_TSHARK2TABE),y)
obj-y += sensor_power_tshark2tabe.o
else ifeq ($(CONFIG_SS_GRANDPRIME3G_VE),y)
obj-y += sensor_power_grandprime3g_ve.o
else ifeq ($(CONFIG_SS_SHARKLT8),y)
obj-y += sensor_power_sharkl_t8.o
else ifeq ($(CONFIG_SS_SHARKLT8LIGHTSLEEP),y)
obj-y += sensor_power_sharkl_t8.o
else ifeq ($(CONFIG_SS_GRANDPRIME_DTV),y)
obj-y += sensor_power_grandprime_dtv.o
else ifeq ($(CONFIG_SS_COREPRIME3G_VE),y)
obj-y += sensor_power_coreprime3g_ve.o
else ifeq ($(CONFIG_SS_SHARKLS_Z3LTE),y)
obj-y += sensor_power_sharkls_z3lte.o
else ifeq ($(CONFIG_SS_SHARKL_J1POPLTE),y)
obj-y += sensor_power_sharkl_j1poplte.o
else ifeq ($(CONFIG_MACH_SP9830I_J3LTE),y)
obj-y += sensor_power_sharkls_j3lte.o
else ifeq ($(CONFIG_MACH_J3_3G),y)
obj-y += sensor_power_sharkls_j3lte.o
else ifeq ($(CONFIG_MACH_SP9830I_J2LTE),y)
obj-y += sensor_power_sharkls_j2lte.o
else ifeq ($(CONFIG_SS_TIZENZ3_3G),y)
obj-y += sensor_power_sharkls_z3lte.o
else
obj-y += sensor_power.o
endif
